### ISSUE TITLE
[ItemPoolLimiter] Incompatibility with the FW_Artifacts mod

### ISSUE THREAD

**Issue by MightyW0lf** [kking117/RoR2-kking117Mods#1]
The ItemPoolLimiter doesn't work with the [FW_Artifacts](https://thunderstore.io/package/RyanPallesen/FW_Artifacts/) mod. No artifact from that mod needs to be activated, having the mod installed along with the ItemPoolLimiter mod is enough.

[Demonstration video](https://youtu.be/pAt5dx4YWQM) - see [LogOutput.log](https://github.com/kking117/RoR2-kking117Mods/files/6182413/LogOutput.log) for configured limitations which don't get applied in the video.

Mods installed:
- bbepis-BepInExPack-5.3.1
- tristanmcpherson-R2API-2.5.14
- Harb-DebugToolkit-3.4.2
- kking117-ItemPoolLimiter-1.1.0
- RyanPallesen-FW_Artifacts-1.0.1

**Comment by RyanPallesen** [comment]
Is this a bad IL hook? fw_artifacts has a .on hook for populate scene that seems to be the problem?

**Comment by RyanPallesen** [comment]
Calling the following breaks your mod:

  Run.instance.BuildDropTable();

                        typeof(PickupTransmutationManager).GetMethod("RebuildPickupGroups", BindingFlags.NonPublic | BindingFlags.Static).Invoke(null, new object[0]);
                        
                        is fixed in latest release of fw_artifacts.

**Comment by kking117** [comment]
I will hopefully fix this in the next update.

**Comment by MightyW0lf** [comment]
Looks like it's fixed!
