### ISSUE TITLE
[AgileSaw] Suggestion: Add configs for Loader's Grapple / Spiked Fist

### ISSUE THREAD

**Issue by bonjorno7** [kking117/RoR2-kking117Mods#17]
In my opinion any ability which does not auto fire, has a cooldown and/or charge time, or stops sprint but allows the user to immediately start sprinting again, should be agile.
No longer needing to turn sprint on again after starting Charged Gauntlet is such a relief, and I'd love to have the same for grapling and perhaps pylon throwing / thunder slamming too.
I guess my definition includes captains shotgun, but perhaps that'd be overpowered, especially in combination with an auto fire mod.

**Comment by bonjorno7** [comment]
Oh awesome, thank you so much! In that case I'm gonna write down some more suggestions :p
- Commando
  - Frag Grenade (could be overpowered if it allows you to throw it further, not sure)
- Engineer
  - Pressure Mines
  - Spider Mines
  - TR12 Gauss Auto-Turret
  - TR58 Carbonizer Turret
- Mercenary
  - Whilrwind (when using this for movement, it's annoying having to sprint again afterwards, though making this agile might buff certain movement tech to be overpowered, would have to try it to find out).
  - Rising Thunder (I don't generally use this for movement, so perhaps it doesn't belong here)
  - Slicing Winds (could make aiming with it harder, not sure)
- REX
  - DIRECTIVE: Disperse (could be weird, could be nice, honestly not sure)
  - Bramble Volley (could be weird, could be nice, honestly not sure)
  - DIRECTIVE: Harvest
  - Tangling Growth
-  Loader
  - Thunder Gauntlet (while less important for this than for the default utility skill, I still think it makes sense for it to be agile too)
- Acrid
  - Ravenous Bite (you can immediately start sprinting after pressing the button, and it doesn't interrupt the attack)
- Captain
  - Power Taser (if shotgun can be agile, this can be too)
- Railgunner
  - Supercharge (at least the charging itself, I usually sprint while waiting for it)
  - Cryocharge (at least the charging itself, I usually sprint while waiting for it)

**Comment by kking117** [comment]
I've added all these with the latest update. I've also included a configuration to make any other skills agile by the name token they use, specifically for modded characters and skills.

**Comment by bonjorno7** [comment]
Awesome thank you so much!
I guess that means you can close this issue, if you want.
