### ISSUE TITLE
FlatItemBuff: Stacking Old War Stealthkit creates infinite shields from Transcendence/Shared Design

### ISSUE THREAD

**Issue by Firmamental** [kking117/RoR2-kking117Mods#20]
When combining the stealthkit and either a transcendence or shared design, falling to low health or triggering OSP will immediately begin to recharge the shields, allowing OSP to reset before the invisibility ends. That makes sense and is fun, but if enough stealthkits are stacked, there is no downtime to this ability, making the player essentially invulnerable to most damage.

**Comment by kking117** [comment]
Shields recharge when "out of danger", which is why it happens so I can't change how this works easily. As far as being game breaking it isn't reliable and usually locks you out of healing.

**Comment by kking117** [comment]
I could make it so that the Combat and Danger cancel lasts for a 1 second instead of the full buff duration.

**Comment by Firmamental** [comment]
I think if it were to force you out, it would work better, aye
then it would function essentially the same, allowing a much faster recovery when put in stealth, but if you get hit repeatedly, it doesn't enable broken combos

**Comment by kking117** [comment]
> I think if it were to force you out

This is a bit vague for me to understand, so I'll explain my two ideas of what I think this means.

**Idea 1**

It keeps you out of Combat and Danger for a second instead of the full buff duration.

**Idea 2**

The buff's duration is reduced whenever you take damage (likely affected by its proc coefficient).

**Comment by Firmamental** [comment]
> > I think if it were to force you out
> 
> This is a bit vague for me to understand, so I'll explain my two ideas of what I think this means.
> 
> **Idea 1**
> 
> It keeps you out of Combat and Danger for a second instead of the full buff duration.
> 
> **Idea 2**
> 
> The buff's duration is reduced whenever you take damage (likely affected by its proc coefficient).

Oh, sorry if I was unclear, I meant the first one! That or just toggling danger/combat once without a timer where it stays no matter what, but one second is close enough that it's essentially the same idea

**Comment by kking117** [comment]
I've added it to the 1.13.2 version of the mod. You can close this issue at your leisure.
