### ISSUE TITLE
[Flat Item Buff] Potential lockup when loading in?

### ISSUE THREAD

**Issue by Coffe-e** [kking117/RoR2-kking117Mods#23]
Currently unable to start modded and fully load in with FlatItemBuff installed, though I do not know the cause why. I suspect it's some form of mod incompatibility with mystic's items but i'm unsure. Here's the log:
[LogOutput.log](https://github.com/kking117/RoR2-kking117Mods/files/10273739/LogOutput.log)

**Comment by kking117** [comment]
From what I can tell from the log it's an incompatibility between RiskyMod and the rework to Titanic Knurl. I'd suggest disabling all changes to Titanic Knurl in either FlatItemBuff or RiskyMod.

**Comment by Coffe-e** [comment]
Oh right! I completely forgot since I moved over to the mod manager that all my configs were reset, so I gotta do that, thanks for telling me though! I'll see if it works.

**Comment by Coffe-e** [comment]
Yeah that was the hangup, thanks for reminding me about that!
