### ISSUE TITLE
Flatitembuff Infusion

### ISSUE THREAD

**Issue by Khorneflakes1** [kking117/RoR2-kking117Mods#24]
Your version of infusion was my favorite, I thought it was pretty simple and elegant compared to most infusion reworks. Could you bring it back? You have two options for most of your reworks anyways.

**Comment by kking117** [comment]
Okay it's added back in 1.15.2 update, however some configs have not been included for simplicity. The big one that was removed is that minions don't give their owner infusion samples they've created.

**Comment by Khorneflakes1** [comment]
Thanks! The lost features are a shame, but it's not that big of a deal.
