### ISSUE TITLE
ItemPoolLimiter update?

### ISSUE THREAD

**Issue by Blastinburn** [kking117/RoR2-kking117Mods#27]
Is there any chance to update ItemPoolLimiter?  With even a few item/expansion mods the pool balloons a lot so getting mobility and healing is much harder and there isn't really another mod that does anything like this one.

**Comment by kking117** [comment]
It was discontinued a good while before Survivors of the Void. If you're looking for something similar try ItemRoulette by ZeusesNeckMeat: https://thunderstore.io/package/ZeusesNeckMeat/ItemRoulette/
