### ISSUE TITLE
[ItemPoolLimiter] Request: Item Whitelist in config

### ISSUE THREAD

**Issue by AndyDoe** [kking117/RoR2-kking117Mods#3]
I rather enjoy this mod enabling more vanilla-like item distribution in modded play with tons of items, but some items feel too important to go without in a run, like Hoof or Glasses. So I want to propose a whitelist feature in the config that guarantees certain items will be placed in the pool, not counting against the configured pool size limit.

**Comment by cobaltw** [comment]
Second this, I've been wanting to use this mod but the inability to whitelist items is the only reason I haven't kept it in my usual mod list

**Comment by kking117** [comment]
I've decided to officially stop supporting the mod. I haven't supported it for several months and don't plan to in the future as far as I can see.
