### ISSUE TITLE
[ItemPoolLimiter] Suggestion: Option to expand the pool with each stage

### ISSUE THREAD

**Issue by MightyW0lf** [kking117/RoR2-kking117Mods#4]
Option to add N items to the item pool with each stage. N would be configurable, ideally for each rarity separately. Maybe with a report in chat which items have been added to the pool at the start of each stage?

This would serve as a less radical alternative to the curent `Disable Stage` configuration.

**Comment by kking117** [comment]
I've decided to officially stop supporting the mod. I haven't supported it for several months and don't plan to in the future as far as I can see.
