### ISSUE TITLE
[ArtifactOfGrief] Setting 'Order Tier' configuration option to 'false' breaks stuff

### ISSUE THREAD

**Issue by MightyW0lf** [kking117/RoR2-kking117Mods#5]
When the `Order Tier` configuration option is set to `false`, these (and possibly more?) bugs occur:

* `Drop Threshold` configuration option doesn't work?
* Only Boss tier items are dropped?

Both demonstrated in [this video](https://youtu.be/AE_hGSxTegk), capturing gameplay with default configuration except for these options:

* `Order Tier = false`
* `Drop Threshold = 0.5`
    * Yet items still drop even after a Lesser Wisp hit.

Mods installed:

- bbepis-BepInExPack-5.4.9
- tristanmcpherson-R2API-3.0.43
- RiskofThunder-HookGenPatcher-1.2.1
- **kking117-ArtifactOfGrief-2.0.0**
- IHarbHD-DebugToolkit-3.5.1
- XoXFaby-MMHOOK_Standalone-1.0.3
- kinggrinyov-AutoSkipIntroCutscene-1.0.2

[LogOutput.log](https://github.com/kking117/RoR2-kking117Mods/files/6634084/LogOutput.log) from the video.

**Comment by kking117** [comment]
The mod has been updated to hopefully fix this issue with `Order Tier`.

`Drop Threshold` was specifically for dropping more than 1 item, however that has now been changed in this update to be the minimum amount of damage required to drop at least 1 item.

**Comment by MightyW0lf** [comment]
My bad about the `Drop Threshold`, must've read it wrong. Nice change though, makes more sense now :)
