### ISSUE TITLE
[bug] in multiplayer clients receive thousands of calls

### ISSUE THREAD

**Issue by notjac0b** [kking117/RoR2-kking117Mods#8]
the following shows up thousands of times in the log
---------------------------------------------------
[Info   : Unity Log] (-22.3, 0.0, -12.1)
[Warning: Unity Log] [Server] function 'System.Void RoR2.CharacterMaster::SetLoadoutServer(RoR2.Loadout)' called on client
[Warning: Unity Log] [Server] function 'System.Void RoR2.MinionOwnership::SetOwner(RoR2.CharacterMaster)' called on client
[Warning: Unity Log] [Server] function 'System.Void RoR2.Inventory::GiveItem(RoR2.ItemDef,System.Int32)' called on client
[Error  : Unity Log] SpawnObject for TitanGoldAllyMaster(Clone) (UnityEngine.GameObject), NetworkServer is not active. Cannot spawn objects without an active server.
[Warning: Unity Log] [Server] function 'RoR2.CharacterBody RoR2.CharacterMaster::Respawn(UnityEngine.Vector3,UnityEngine.Quaternion)' called on client
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
AurelioniteStuck.MainPlugin.<Awake>g__AddTitanInventory|17_11 (RoR2.CharacterMaster titan, System.Int32 seeds) (at <69227fc5ed69498db1bbb69579ea2bea>:IL_0050)
AurelioniteStuck.MainPlugin.<Awake>g__CreateTitanGoldCombatSquad|17_9 (RoR2.TeamIndex team, System.Int32 SeedCount) (at <69227fc5ed69498db1bbb69579ea2bea>:IL_00AF)
AurelioniteStuck.MainPlugin.<Awake>b__17_1 (On.RoR2.Run+orig_FixedUpdate orig, RoR2.Run self) (at <69227fc5ed69498db1bbb69579ea2bea>:IL_009C)
DMD<>?-1892111616.Hook<RoR2.Run::FixedUpdate>?1350699520 (RoR2.Run ) (at <d91656cf4b1b4f9396b8c6a17dedc82f>:IL_0014)
DMD<>?-1892111616.Trampoline<RoR2.Run::FixedUpdate>?-605538304 (RoR2.Run ) (at <fb562f38547144418fc58c2774bdd49d>:IL_0020)
ThinkInvisible.ClassicItems.HitList.On_RunFixedUpdate (On.RoR2.Run+orig_FixedUpdate orig, RoR2.Run self) (at <f12240b757ee4df5a23e3fa25869943f>:IL_0000)
DMD<>?-1892111616.Hook<RoR2.Run::FixedUpdate>?-1240170624 (RoR2.Run ) (at <51b28806842e4625a33f8ef751d13373>:IL_0014)
-----------------------------------------------------

Clients dropped to 1 frame per second host was fine.
also this line repeats many times: 
[Warning: Unity Log] Trying to send command for object without authorit
be warned massive 23MB log.
[LogOutput.log](https://github.com/kking117/RoR2-kking117Mods/files/7406969/LogOutput.log)
y.

**Comment by kking117** [comment]
I've done a quick test with a friend and may have fixed the client call issue, I'd suggest testing it with DebugToolKit to confirm for yourself quickly.
