### ISSUE TITLE
[Suggestion] Few more functionalities for banner areas

### ISSUE THREAD

**Issue by HR-UP** [kking117/RoR2-kking117Mods#9]
Hi. Is it possible to track inside how many banner zones player are in? It would be great if bonus from several zones affecting player at once would give a few more % to it's effect (and/or heal, move speed, attack speed) and/or it would increase the time buff effect persist after you leave the banners area. So when you live a single banner area you get like 1-2 sec of residual buff effect, and if have left 2-3 banners that overlap you get like 5-6 sec or so. Would be great if it can be configurable.

**Comment by kking117** [comment]
I don't think it's possible to track players in the zones, so this may or may not be possible. (Also sorry for the late reply.)
